### ISSUE TITLE
Add remaining DCW questionnaires

### ISSUE THREAD

**Issue by mcjustin** [uwcirg/asbi-screening-app#34]
The DCW team chose these by browsing the NLM form manager, in order to make this task easier.

- Everyday Cognition (ECOG) 12 (short form) - Justin found 89133-3
- Everyday Cognition Care Partner Assessment (ECog-12 Care Partner)
- "Cognitive Impairment - St. Louis University Mental Status (SLUMS) Examination [SLUMS] [71947-6]"
- "ADLs/IADLs - Functional Impairment" 69337-4
- "BEHAVE 5+"
- Generalized anxiety disorder 7 items (GAD-7) [69737-5] (may have elsewhere already)
- Geriatric depression scale (GDS).short version panel [48543-3]
- Indicators of depression, anxiety, sad mood [45997-4] (Cornell Scale of Depression in Dementia)

**Comment by mcjustin** [comment]
@achen2401 just a heads-up - I'm aiming to add these this week.

**Comment by mcjustin** [comment]
@achen2401  I did the ECOG as an example. Downloaded from NLM w/ status "active", and then committed as new file in https://github.com/uwcirg/asbi-screening-app/pull/35 . Then I made these changes there: https://github.com/uwcirg/asbi-screening-app/pull/35/commits/23d9bc5b7e5f61c841cc597c272f1b266cc2cce2 .  Note that I did not remove item.code.display - too much work for a questionnaire of this size, fine to not do that moving forward.

**Comment by mcjustin** [comment]
@achen2401  If you're unable to find these at NLM, or aren't sure if you've found the correct one there, please ask @sierramatice .

**Comment by achen2401** [comment]
@mcjustin & @sierramatice  I am not able to find the following questionnaires in NLM:

- Everyday Cognition Care Partner Assessment (ECog-12 Care Partner)
- BEHAVE 5+ 

Will you help me find them?  (If you have the LOINC code for each, I can just look up in NLM)

Also,  for `Cognitive Impairment - St. Louis University Mental Status (SLUMS) Examination [SLUMS] [71947-6]`, the one I found in NLM has no question in it?  Perhaps the LOINC code is not correct?

Also the `Everyday Cognition (ECOG) 12 (short form) [89133-3]` questionnaire has around **40** questions, a pretty long questionnaire, just want to make sure that that is the one they want.

**Comment by mcjustin** [comment]
@achen2401 : Sie-Ce is out, returning next Thursday. Can you please switch gears and just add the GAD7 (recall that we are aiming to administer that next week), and whatever you've already completed into a MR?

**Comment by achen2401** [comment]
thanks, @mcjustin I did add GAD7 and have started a separate MR [here](https://github.com/uwcirg/asbi-screening-app/pull/37)  (note its base branch is `add-more-dcw-questionnaires`).  The MR should allow administration of of both gad7 y phq9 in sequence.

**Comment by sierramatice** [comment]
@achen2401 this document has the questionnaires content they want in it to compare what you have found to! https://uwnetid.sharepoint.com/:w:/s/og_sadakresearch/EdDB0d-MUyBKtAVzaFGj5REB4LahDiwsKA65soXUJBK55Q?e=nvEMff

and the ECog-12 Care Partner is the same as the ECog-12, just asked of the care partner instead of the patient, as the ECog-12 is not 40 questions long! it is 12 questions long. 

Here are links to the pdf versions of BEHAVE5+ 
https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s
and Cognitive Impairment - St. Louis University Mental Status (SLUMS) Examination [SLUMS] [71947-6]
https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s
for reference
and the ECog-12 Care Partner is the same as the ECog-12, just asked of the care partner instead of the patient, as the ECog-12 is not 40 questions long! it is 12 questions long. 

Here are links to the pdf versions of BEHAVE5+ 
https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s
and Cognitive Impairment - St. Louis University Mental Status (SLUMS) Examination [SLUMS] [71947-6]
https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s
for reference

**Comment by sierramatice** [comment]
@achen2401 this document has the questionnaires content they want in it to compare what you have found to! https://uwnetid.sharepoint.com/:w:/s/og_sadakresearch/EdDB0d-MUyBKtAVzaFGj5REB4LahDiwsKA65soXUJBK55Q?e=nvEMff

and the ECog-12 Care Partner is the same as the ECog-12, just asked of the care partner instead of the patient, as the ECog-12 is not 40 questions long! it is 12 questions long. 

Here are links to the pdf versions of BEHAVE5+ 
https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s
and Cognitive Impairment - St. Louis University Mental Status (SLUMS) Examination [SLUMS] [71947-6]
https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s
for reference

**Comment by achen2401** [comment]
@sierramatice thank you.  Now that I am looking at the SLUMS questionnaire from https://drive.google.com/drive/folders/1Z7Kag28PoKYdttRgy8q1ndzX1nsM0h_s  I realize now why the SLUMS from NLM has only 1 question (for total score).  Can you confirm that the SLUMS form should only contain **one** item for the staff to record the total score?

**Comment by achen2401** [comment]
@sierramatice Should there be two ECog-12 questionnaires, **one for the patient, and one for the care partner** ? since the content of each is slightly different from each other?

**Comment by sierramatice** [comment]
@achen2401 I think for the MVP the one question to log the questionnaire will work great for SLUMS (as it has a lot of on paper work similar to the mini cog) and yes there should be **Two different** ECog-12s !

**Comment by achen2401** [comment]
@sierramatice For **Cornell Scale of Depression in Dementia** questionnaire, they have indicated the LOINC code, **45997-4** for the questionnaire in the document, https://uwnetid.sharepoint.com/:w:/s/og_sadakresearch/EdDB0d-MUyBKtAVzaFGj5REB4LahDiwsKA65soXUJBK55Q?e=nvEMff.  I used that LOINC code to search for the questionnaire in the NLM form manager.  The query returns a questionnaire whose content seems different from the content of the questionnaire indicated in the google doc.  Can you verify if the attached is what they want for Cornell Scale of Depression in Dementia?
[Indicators-of-depression,-anxiety,-sad-mood.R4 (2).json.zip](https://github.com/uwcirg/asbi-screening-app/files/9803384/Indicators-of-depression.-anxiety.-sad-mood.R4.2.json.zip)

**Comment by achen2401** [comment]
@mcjustin & @sierramatice I am at a stopping point now for changes to add questionnaires.  Will you review this [PR](https://github.com/uwcirg/asbi-screening-app/pull/35) when you have a moment.  I am hoping the content for each of the questionnaires that I added will match up to what is expected in the [specs](https://uwnetid.sharepoint.com/:w:/s/og_sadakresearch/EdDB0d-MUyBKtAVzaFGj5REB4LahDiwsKA65soXUJBK55Q?e=nvEMff)
